/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Juego;
import controlador.gestion_BD;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.*;
import java.security.Principal;
import java.util.ArrayList;

import javax.swing.*;

import modelo.Carta;
import modelo.EnumRegiones;

/**
 *
 * @author Antonio
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener{
    private javax.swing.JButton[][] cartasItems;
    private ArrayList <ImageIcon> imagenesCartas;
    private String nombreJugador;
    private int[] BTN_LONG={2,10};// La longitud del array de botones.
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroUsuario = new javax.swing.JFrame();
        panelVacio1Registro = new javax.swing.JPanel();
        panelCentralRegistro = new javax.swing.JPanel();
        textFieldNombreUsuarioRegistro = new javax.swing.JTextField();
        textFieldEdadUsuarioRegistro = new javax.swing.JTextField();
        comboBoxRegionesRegistro = new javax.swing.JComboBox<>();
        labelSuperiorRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnReset1 = new javax.swing.JButton();
        btnEnviarRegistro = new javax.swing.JButton();
        btnVolverRegistro = new javax.swing.JButton();
        textFieldPasswordUsuarioRegistro = new javax.swing.JPasswordField();
        panelVacio2Registro = new javax.swing.JPanel();
        logIn = new javax.swing.JFrame();
        panelVacio1Login = new javax.swing.JPanel();
        panelCentralLogin = new javax.swing.JPanel();
        labelSuperiorRegistro1 = new javax.swing.JLabel();
        labelNombreLogIn = new javax.swing.JLabel();
        labelPWDLogIn = new javax.swing.JLabel();
        textFieldNombreUsuarioLogIn = new javax.swing.JTextField();
        btnResetLogIn = new javax.swing.JButton();
        btnEnviarLogIn = new javax.swing.JButton();
        btnVolverLogIn = new javax.swing.JButton();
        textFieldPasswordUsuarioLogIn = new javax.swing.JPasswordField();
        panelVacio2Login = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JFrame();
        panelIzquierda = new javax.swing.JPanel();
        btnPelea = new javax.swing.JButton();
        labelBatalla = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelColeccion = new javax.swing.JPanel();
        labelColeccion = new javax.swing.JLabel();
        panelSuperiorVacio = new javax.swing.JPanel();
        panelCartas = new javax.swing.JPanel();
        panelDerecha = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        labelTienda1 = new javax.swing.JLabel();
        panelMonedas = new javax.swing.JPanel();
        panelIconoMoneda = new javax.swing.JPanel();
        labelIconoMoneda = new javax.swing.JLabel();
        labelNumeroMonedas = new javax.swing.JLabel();
        dialogLogInFallido = new javax.swing.JDialog();
        panelIconoAviso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        btnAceptarDialog = new javax.swing.JButton();
        cartaAmpliada = new javax.swing.JDialog();
        dialogSobre = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        dialogWIP = new javax.swing.JDialog();
        panelIconoAviso1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelWIP = new javax.swing.JLabel();
        btnAceptarDialogWIP = new javax.swing.JButton();
        dialogMercaderes = new javax.swing.JDialog();
        panelIconoAviso2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        labelMercaderes = new javax.swing.JLabel();
        btnAceptarDialogMercaderes = new javax.swing.JButton();
        panelVacio1 = new javax.swing.JPanel();
        panelCentral1 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelMPT = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        panelVacio3 = new javax.swing.JPanel();

        registroUsuario.setMinimumSize(new java.awt.Dimension(1920, 1080));
        registroUsuario.setResizable(false);
        registroUsuario.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacio1RegistroLayout = new javax.swing.GroupLayout(panelVacio1Registro);
        panelVacio1Registro.setLayout(panelVacio1RegistroLayout);
        panelVacio1RegistroLayout.setHorizontalGroup(
            panelVacio1RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio1RegistroLayout.setVerticalGroup(
            panelVacio1RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        registroUsuario.getContentPane().add(panelVacio1Registro);

        textFieldNombreUsuarioRegistro.setToolTipText("Nombre");
        textFieldNombreUsuarioRegistro.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldNombreUsuarioRegistro.setPreferredSize(new java.awt.Dimension(50, 100));

        textFieldEdadUsuarioRegistro.setToolTipText("Contraseña");
        textFieldEdadUsuarioRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldEdadUsuarioRegistro.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldEdadUsuarioRegistro.setPreferredSize(new java.awt.Dimension(50, 100));
        textFieldEdadUsuarioRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldEdadUsuarioRegistroKeyPressed(evt);
            }
        });

        comboBoxRegionesRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUW", "EUNE", "KOR", "NA", "LATAM", "CHI", "JAP", "RUS", "AFR", "OCE" }));

        labelSuperiorRegistro.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelSuperiorRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuperiorRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Registrar_label.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Edad_label.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Region_label.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Password_label.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Nombre_label.png"))); // NOI18N

        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Borrar_button.png"))); // NOI18N
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        btnEnviarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Enviar_button.png"))); // NOI18N
        btnEnviarRegistro.setPreferredSize(new java.awt.Dimension(72, 24));
        btnEnviarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRegistroActionPerformed(evt);
            }
        });

        btnVolverRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Volver_Button_2_190x64.png"))); // NOI18N
        btnVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCentralRegistroLayout = new javax.swing.GroupLayout(panelCentralRegistro);
        panelCentralRegistro.setLayout(panelCentralRegistroLayout);
        panelCentralRegistroLayout.setHorizontalGroup(
            panelCentralRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldNombreUsuarioRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textFieldEdadUsuarioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboBoxRegionesRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSuperiorRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCentralRegistroLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(panelCentralRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(panelCentralRegistroLayout.createSequentialGroup()
                .addComponent(btnVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textFieldPasswordUsuarioRegistro)
        );
        panelCentralRegistroLayout.setVerticalGroup(
            panelCentralRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralRegistroLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(labelSuperiorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(textFieldNombreUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldPasswordUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldEdadUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(comboBoxRegionesRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEnviarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registroUsuario.getContentPane().add(panelCentralRegistro);

        javax.swing.GroupLayout panelVacio2RegistroLayout = new javax.swing.GroupLayout(panelVacio2Registro);
        panelVacio2Registro.setLayout(panelVacio2RegistroLayout);
        panelVacio2RegistroLayout.setHorizontalGroup(
            panelVacio2RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio2RegistroLayout.setVerticalGroup(
            panelVacio2RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        registroUsuario.getContentPane().add(panelVacio2Registro);

        logIn.setMinimumSize(new java.awt.Dimension(1920, 1080));
        logIn.setResizable(false);
        logIn.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacio1LoginLayout = new javax.swing.GroupLayout(panelVacio1Login);
        panelVacio1Login.setLayout(panelVacio1LoginLayout);
        panelVacio1LoginLayout.setHorizontalGroup(
            panelVacio1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        panelVacio1LoginLayout.setVerticalGroup(
            panelVacio1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
        );

        logIn.getContentPane().add(panelVacio1Login);

        labelSuperiorRegistro1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelSuperiorRegistro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuperiorRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/IniciarSesion_label.png"))); // NOI18N

        labelNombreLogIn.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        labelNombreLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Nombre_label.png"))); // NOI18N

        labelPWDLogIn.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        labelPWDLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Password_label.png"))); // NOI18N

        textFieldNombreUsuarioLogIn.setToolTipText("Nombre");
        textFieldNombreUsuarioLogIn.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldNombreUsuarioLogIn.setPreferredSize(new java.awt.Dimension(50, 100));

        btnResetLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Borrar_button.png"))); // NOI18N
        btnResetLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetLogInActionPerformed(evt);
            }
        });

        btnEnviarLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Enviar_button.png"))); // NOI18N
        btnEnviarLogIn.setPreferredSize(new java.awt.Dimension(72, 24));
        btnEnviarLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarLogInActionPerformed(evt);
            }
        });

        btnVolverLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Volver_Button_2_190x64.png"))); // NOI18N
        btnVolverLogIn.setContentAreaFilled(false);
        btnVolverLogIn.setMaximumSize(new java.awt.Dimension(75, 10));
        btnVolverLogIn.setMinimumSize(new java.awt.Dimension(75, 10));
        btnVolverLogIn.setPreferredSize(new java.awt.Dimension(75, 10));
        btnVolverLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCentralLoginLayout = new javax.swing.GroupLayout(panelCentralLogin);
        panelCentralLogin.setLayout(panelCentralLoginLayout);
        panelCentralLoginLayout.setHorizontalGroup(
            panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldNombreUsuarioLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPWDLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNombreLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSuperiorRegistro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCentralLoginLayout.createSequentialGroup()
                .addGroup(panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLoginLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviarLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCentralLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolverLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(textFieldPasswordUsuarioLogIn)
        );
        panelCentralLoginLayout.setVerticalGroup(
            panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLoginLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(labelSuperiorRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(labelNombreLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldNombreUsuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPWDLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldPasswordUsuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnEnviarLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(btnVolverLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logIn.getContentPane().add(panelCentralLogin);

        javax.swing.GroupLayout panelVacio2LoginLayout = new javax.swing.GroupLayout(panelVacio2Login);
        panelVacio2Login.setLayout(panelVacio2LoginLayout);
        panelVacio2LoginLayout.setHorizontalGroup(
            panelVacio2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        panelVacio2LoginLayout.setVerticalGroup(
            panelVacio2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
        );

        logIn.getContentPane().add(panelVacio2Login);

        menuPrincipal.setMinimumSize(new java.awt.Dimension(1920, 1080));
        menuPrincipal.setPreferredSize(new java.awt.Dimension(1920, 1080));
        menuPrincipal.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        btnPelea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Pelea_button.jpg"))); // NOI18N
        btnPelea.setPreferredSize(new java.awt.Dimension(72, 24));
        btnPelea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeleaActionPerformed(evt);
            }
        });

        labelBatalla.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelBatalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBatalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Batalla_label.png"))); // NOI18N

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBatalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzquierdaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPelea, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzquierdaLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(labelBatalla, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(btnPelea, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );

        menuPrincipal.getContentPane().add(panelIzquierda);

        labelColeccion.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelColeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelColeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Coleccion_label.png"))); // NOI18N

        javax.swing.GroupLayout panelSuperiorVacioLayout = new javax.swing.GroupLayout(panelSuperiorVacio);
        panelSuperiorVacio.setLayout(panelSuperiorVacioLayout);
        panelSuperiorVacioLayout.setHorizontalGroup(
            panelSuperiorVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSuperiorVacioLayout.setVerticalGroup(
            panelSuperiorVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        panelCartas.setLayout(new java.awt.GridLayout(10, 2));

        javax.swing.GroupLayout panelColeccionLayout = new javax.swing.GroupLayout(panelColeccion);
        panelColeccion.setLayout(panelColeccionLayout);
        panelColeccionLayout.setHorizontalGroup(
            panelColeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorVacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelColeccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addComponent(panelCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelColeccionLayout.setVerticalGroup(
            panelColeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperiorVacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCartas, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColeccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColeccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuPrincipal.getContentPane().add(panelCentral);

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Comprar_button_1.png"))); // NOI18N
        btnComprar.setPreferredSize(new java.awt.Dimension(72, 24));
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        labelTienda1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelTienda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTienda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Tienda_label.png"))); // NOI18N

        labelIconoMoneda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconoMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/coin.png"))); // NOI18N
        labelIconoMoneda.setFocusable(false);
        labelIconoMoneda.setIconTextGap(0);
        labelIconoMoneda.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelIconoMonedaLayout = new javax.swing.GroupLayout(panelIconoMoneda);
        panelIconoMoneda.setLayout(panelIconoMonedaLayout);
        panelIconoMonedaLayout.setHorizontalGroup(
            panelIconoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIconoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelIconoMonedaLayout.setVerticalGroup(
            panelIconoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIconoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelNumeroMonedas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNumeroMonedas.setText("NUMERO DE MONEDAS");

        javax.swing.GroupLayout panelMonedasLayout = new javax.swing.GroupLayout(panelMonedas);
        panelMonedas.setLayout(panelMonedasLayout);
        panelMonedasLayout.setHorizontalGroup(
            panelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMonedasLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(panelIconoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(labelNumeroMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        panelMonedasLayout.setVerticalGroup(
            panelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(panelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMonedasLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(panelMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelIconoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNumeroMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelDerechaLayout = new javax.swing.GroupLayout(panelDerecha);
        panelDerecha.setLayout(panelDerechaLayout);
        panelDerechaLayout.setHorizontalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMonedas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTienda1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDerechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        panelDerechaLayout.setVerticalGroup(
            panelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTienda1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );

        menuPrincipal.getContentPane().add(panelDerecha);

        dialogLogInFallido.setPreferredSize(new java.awt.Dimension(640, 360));
        dialogLogInFallido.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogLogInFallidoWindowClosed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Warning.png"))); // NOI18N

        javax.swing.GroupLayout panelIconoAvisoLayout = new javax.swing.GroupLayout(panelIconoAviso);
        panelIconoAviso.setLayout(panelIconoAvisoLayout);
        panelIconoAvisoLayout.setHorizontalGroup(
            panelIconoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelIconoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        panelIconoAvisoLayout.setVerticalGroup(
            panelIconoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelIconoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        labelMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/ErrorLogin_label.png"))); // NOI18N

        btnAceptarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Volver_Button_2_190x64.png"))); // NOI18N
        btnAceptarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogLogInFallidoLayout = new javax.swing.GroupLayout(dialogLogInFallido.getContentPane());
        dialogLogInFallido.getContentPane().setLayout(dialogLogInFallidoLayout);
        dialogLogInFallidoLayout.setHorizontalGroup(
            dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                .addGroup(dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(panelIconoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnAceptarDialog)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogLogInFallidoLayout.setVerticalGroup(
            dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIconoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnAceptarDialog)
                .addGap(32, 32, 32))
        );

        cartaAmpliada.setPreferredSize(new java.awt.Dimension(640, 360));

        javax.swing.GroupLayout cartaAmpliadaLayout = new javax.swing.GroupLayout(cartaAmpliada.getContentPane());
        cartaAmpliada.getContentPane().setLayout(cartaAmpliadaLayout);
        cartaAmpliadaLayout.setHorizontalGroup(
            cartaAmpliadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        cartaAmpliadaLayout.setVerticalGroup(
            cartaAmpliadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dialogSobre.setPreferredSize(new java.awt.Dimension(640, 360));

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout dialogSobreLayout = new javax.swing.GroupLayout(dialogSobre.getContentPane());
        dialogSobre.getContentPane().setLayout(dialogSobreLayout);
        dialogSobreLayout.setHorizontalGroup(
            dialogSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSobreLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel3)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        dialogSobreLayout.setVerticalGroup(
            dialogSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSobreLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel3)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        dialogWIP.setPreferredSize(new java.awt.Dimension(640, 360));
        dialogWIP.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogWIPWindowClosed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Warning.png"))); // NOI18N

        javax.swing.GroupLayout panelIconoAviso1Layout = new javax.swing.GroupLayout(panelIconoAviso1);
        panelIconoAviso1.setLayout(panelIconoAviso1Layout);
        panelIconoAviso1Layout.setHorizontalGroup(
            panelIconoAviso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelIconoAviso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        panelIconoAviso1Layout.setVerticalGroup(
            panelIconoAviso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelIconoAviso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        labelWIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/WIP_label.png"))); // NOI18N

        btnAceptarDialogWIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Volver_Button_2_190x64.png"))); // NOI18N
        btnAceptarDialogWIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDialogWIPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogWIPLayout = new javax.swing.GroupLayout(dialogWIP.getContentPane());
        dialogWIP.getContentPane().setLayout(dialogWIPLayout);
        dialogWIPLayout.setHorizontalGroup(
            dialogWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogWIPLayout.createSequentialGroup()
                .addGroup(dialogWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogWIPLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(panelIconoAviso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelWIP, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogWIPLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnAceptarDialogWIP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogWIPLayout.setVerticalGroup(
            dialogWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogWIPLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(dialogWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIconoAviso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnAceptarDialogWIP)
                .addGap(32, 32, 32))
        );

        dialogMercaderes.setPreferredSize(new java.awt.Dimension(640, 360));
        dialogMercaderes.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogMercaderesWindowClosed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Warning.png"))); // NOI18N

        javax.swing.GroupLayout panelIconoAviso2Layout = new javax.swing.GroupLayout(panelIconoAviso2);
        panelIconoAviso2.setLayout(panelIconoAviso2Layout);
        panelIconoAviso2Layout.setHorizontalGroup(
            panelIconoAviso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelIconoAviso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        panelIconoAviso2Layout.setVerticalGroup(
            panelIconoAviso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelIconoAviso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );

        labelMercaderes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/labels/Mercaderes_label.png"))); // NOI18N

        btnAceptarDialogMercaderes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Volver_Button_2_190x64.png"))); // NOI18N
        btnAceptarDialogMercaderes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDialogMercaderesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogMercaderesLayout = new javax.swing.GroupLayout(dialogMercaderes.getContentPane());
        dialogMercaderes.getContentPane().setLayout(dialogMercaderesLayout);
        dialogMercaderesLayout.setHorizontalGroup(
            dialogMercaderesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMercaderesLayout.createSequentialGroup()
                .addGroup(dialogMercaderesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogMercaderesLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(panelIconoAviso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMercaderes, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogMercaderesLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnAceptarDialogMercaderes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogMercaderesLayout.setVerticalGroup(
            dialogMercaderesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMercaderesLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(dialogMercaderesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIconoAviso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMercaderes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnAceptarDialogMercaderes)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MPT");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacio1Layout = new javax.swing.GroupLayout(panelVacio1);
        panelVacio1.setLayout(panelVacio1Layout);
        panelVacio1Layout.setHorizontalGroup(
            panelVacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio1Layout.setVerticalGroup(
            panelVacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(panelVacio1);

        panelTitulo.setEnabled(false);
        panelTitulo.setOpaque(false);

        labelMPT.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelMPT.setForeground(new java.awt.Color(0, 0, 0));
        labelMPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/logo_250x250.png"))); // NOI18N

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMPT, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMPT, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/IniciarSesion_button.png"))); // NOI18N
        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(72, 24));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/botones/Registrar_button.png"))); // NOI18N
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Medieval Pixel Tokens");

        javax.swing.GroupLayout panelCentral1Layout = new javax.swing.GroupLayout(panelCentral1);
        panelCentral1.setLayout(panelCentral1Layout);
        panelCentral1Layout.setHorizontalGroup(
            panelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCentral1Layout.setVerticalGroup(
            panelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelCentral1);

        javax.swing.GroupLayout panelVacio3Layout = new javax.swing.GroupLayout(panelVacio3);
        panelVacio3.setLayout(panelVacio3Layout);
        panelVacio3Layout.setHorizontalGroup(
            panelVacio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio3Layout.setVerticalGroup(
            panelVacio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(panelVacio3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEdadUsuarioRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldEdadUsuarioRegistroKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            this.textFieldEdadUsuarioRegistro.setEditable(true);
            try {
                Integer.valueOf(this.textFieldEdadUsuarioRegistro.getText());
            } catch (NumberFormatException e) {
                this.textFieldEdadUsuarioRegistro.setText("");
            }
        } else {
            this.textFieldEdadUsuarioRegistro.setText("* Introduce solo números(0-9)");
        }
    }//GEN-LAST:event_textFieldEdadUsuarioRegistroKeyPressed

    private void btnEnviarLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarLogInActionPerformed
        if (!(gestion_BD.iniciarSesion(this.textFieldNombreUsuarioLogIn.getText(),
                this.textFieldPasswordUsuarioLogIn.getText()))) { // Si no se puede iniciar sesión
            
            this.dialogLogInFallido.setVisible(true);
            this.logIn.setFocusable(false);
        }else{
            this.menuPrincipal.setVisible(true);
            this.logIn.setVisible(false);
            nombreJugador = this.textFieldNombreUsuarioLogIn.getText(); //Si hace login, pilla el texto del textField (que es igual al nombre de la BD)
            
            //TODO he metido esto aqui porque en el otro metodo no lo hacia
            this.labelNumeroMonedas.setText(String.valueOf(gestion_BD.obtenerCantidadMonedas(nombreJugador))); //Pilla las monedas del jugador
            crearEspacioDeCartas();
        }
    }//GEN-LAST:event_btnEnviarLogInActionPerformed

    private void btnResetLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetLogInActionPerformed
        this.textFieldNombreUsuarioLogIn.setText("");
        this.textFieldPasswordUsuarioLogIn.setText("");
    }//GEN-LAST:event_btnResetLogInActionPerformed

    private void btnEnviarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRegistroActionPerformed
        if (gestion_BD.altaUsuario( textFieldNombreUsuarioRegistro.getText(),
                                    textFieldPasswordUsuarioRegistro.getText(),
                                    Integer.parseInt(textFieldEdadUsuarioRegistro.getText()),
                                    comboBoxRegionesRegistro.getSelectedItem().toString())) {
            
        }
    }//GEN-LAST:event_btnEnviarRegistroActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        this.logIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        this.registroUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnAceptarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDialogActionPerformed
        this.dialogLogInFallido.setVisible(false);
        this.textFieldNombreUsuarioLogIn.setText("");
        this.textFieldPasswordUsuarioLogIn.setText("");
    }//GEN-LAST:event_btnAceptarDialogActionPerformed

    private void btnVolverLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLogInActionPerformed
        this.logIn.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnVolverLogInActionPerformed

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        this.registroUsuario.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void dialogLogInFallidoWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogLogInFallidoWindowClosed
        this.textFieldNombreUsuarioLogIn.setText("");
        this.textFieldPasswordUsuarioLogIn.setText("");
    }//GEN-LAST:event_dialogLogInFallidoWindowClosed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if (Integer.parseInt(this.labelNumeroMonedas.getText()) <= 0) { //Mira si no hay liquidez
            this.dialogMercaderes.setVisible(true);
        }else{
            ArrayList<Carta> listaCartasSobre = Juego.abrirSobre(); //lista que se va a mostrar en el dialog

            boolean comprado = gestion_BD.comprar(nombreJugador); 

            if (comprado) { //Si el update se ha hecho correctamente
                this.labelNumeroMonedas.setText(String.valueOf(Integer.parseInt(this.labelNumeroMonedas.getText()) - 100)); //Actualiza el label de las monedas
            }
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        this.textFieldNombreUsuarioRegistro.setText("");
        this.textFieldPasswordUsuarioRegistro.setText("");
        this.textFieldEdadUsuarioRegistro.setText("");
        this.comboBoxRegionesRegistro.setSelectedItem("EUW");
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnAceptarDialogWIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDialogWIPActionPerformed
        this.dialogWIP.setVisible(false);
        this.menuPrincipal.setFocusable(true);
    }//GEN-LAST:event_btnAceptarDialogWIPActionPerformed

    private void dialogWIPWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogWIPWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogWIPWindowClosed

    private void btnAceptarDialogMercaderesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDialogMercaderesActionPerformed
        this.dialogMercaderes.setVisible(false);
    }//GEN-LAST:event_btnAceptarDialogMercaderesActionPerformed

    private void dialogMercaderesWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogMercaderesWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogMercaderesWindowClosed

    private void btnPeleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeleaActionPerformed
        this.dialogWIP.setVisible(true);
        this.menuPrincipal.setFocusable(false);
    }//GEN-LAST:event_btnPeleaActionPerformed

    public void mostrarDialogoLogInFallido(){
        this.dialogLogInFallido.setVisible(true);
        this.setFocusable(false);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    public void crearEspacioDeCartas(){
        panelCartas.setLayout(new java.awt.GridLayout(BTN_LONG[0],BTN_LONG[1]));
        for (int i = 0; i < BTN_LONG[0]; i++) {
            for (int j = 0; j < BTN_LONG[1]; j++) {
                cartasItems[i][j] = new javax.swing.JButton(); //inicio boton
                panelCartas.add(cartasItems[i][j]); //añado boton al panel para que se vea
                ImageIcon fotoCarta = new ImageIcon(getClass().getResource("/resources/img/Incognita_card.png"));
                Image scaledImage = fotoCarta.getImage();
                scaledImage = scaledImage.getScaledInstance(fotoCarta.getIconWidth()/2, fotoCarta.getIconHeight()/2, java.awt.Image.SCALE_SMOOTH);
                fotoCarta = new ImageIcon(scaledImage);
                cartasItems[i][j].setSize(fotoCarta.getIconWidth()/2,fotoCarta.getIconHeight()/2);
                cartasItems[i][j].setIcon(fotoCarta);
                cartasItems[i][j].addActionListener(this);
                cartasItems[i][j].setBackground(new Color(245,245,245)); //color del fonto del boton
                cartasItems[i][j].setFocusable(false); //esto hace que no se pueda enfocar el boton y no salga un recuadro raro feo
                cartasItems[i][j].setFont(new Font("Arial",Font.BOLD,120)); //la font de las letras dentro del boton
            }
        } //Te lo subo?
        panelCartas.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarDialog;
    private javax.swing.JButton btnAceptarDialogMercaderes;
    private javax.swing.JButton btnAceptarDialogWIP;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEnviarLogIn;
    private javax.swing.JButton btnEnviarRegistro;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnPelea;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnResetLogIn;
    private javax.swing.JButton btnVolverLogIn;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JDialog cartaAmpliada;
    private javax.swing.JComboBox<String> comboBoxRegionesRegistro;
    private javax.swing.JDialog dialogLogInFallido;
    private javax.swing.JDialog dialogMercaderes;
    private javax.swing.JDialog dialogSobre;
    private javax.swing.JDialog dialogWIP;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelBatalla;
    private javax.swing.JLabel labelColeccion;
    private javax.swing.JLabel labelIconoMoneda;
    private javax.swing.JLabel labelMPT;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelMercaderes;
    private javax.swing.JLabel labelNombreLogIn;
    private javax.swing.JLabel labelNumeroMonedas;
    private javax.swing.JLabel labelPWDLogIn;
    private javax.swing.JLabel labelSuperiorRegistro;
    private javax.swing.JLabel labelSuperiorRegistro1;
    private javax.swing.JLabel labelTienda1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelWIP;
    private javax.swing.JFrame logIn;
    private javax.swing.JFrame menuPrincipal;
    private javax.swing.JPanel panelCartas;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCentral1;
    private javax.swing.JPanel panelCentralLogin;
    private javax.swing.JPanel panelCentralRegistro;
    private javax.swing.JPanel panelColeccion;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIconoAviso;
    private javax.swing.JPanel panelIconoAviso1;
    private javax.swing.JPanel panelIconoAviso2;
    private javax.swing.JPanel panelIconoMoneda;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelMonedas;
    private javax.swing.JPanel panelSuperiorVacio;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelVacio1;
    private javax.swing.JPanel panelVacio1Login;
    private javax.swing.JPanel panelVacio1Registro;
    private javax.swing.JPanel panelVacio2Login;
    private javax.swing.JPanel panelVacio2Registro;
    private javax.swing.JPanel panelVacio3;
    private javax.swing.JFrame registroUsuario;
    private javax.swing.JTextField textFieldEdadUsuarioRegistro;
    private javax.swing.JTextField textFieldNombreUsuarioLogIn;
    private javax.swing.JTextField textFieldNombreUsuarioRegistro;
    private javax.swing.JPasswordField textFieldPasswordUsuarioLogIn;
    private javax.swing.JPasswordField textFieldPasswordUsuarioRegistro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        JLabel labelimagen = new JLabel("", JLabel.CENTER);
        ImageIcon fotoCarta = new ImageIcon(getClass().getResource("/resources/img/Alquimista_card.png"));
        Image scaledImage = fotoCarta.getImage();
        scaledImage = scaledImage.getScaledInstance(fotoCarta.getIconWidth()*2, fotoCarta.getIconHeight() * 2, java.awt.Image.SCALE_SMOOTH);
        fotoCarta = new ImageIcon(scaledImage);
        labelimagen.setIcon(fotoCarta);
        labelimagen.setSize(fotoCarta.getIconWidth(), fotoCarta.getIconHeight());
        cartaAmpliada.add(labelimagen);
        cartaAmpliada.setSize(fotoCarta.getIconWidth()+16, fotoCarta.getIconHeight()+39);
        cartaAmpliada.setLocationRelativeTo(null);
        cartaAmpliada.setVisible(true);
    }
    
    public void cargarFotosCartas(ArrayList <Carta> listaTodasCartas) {
        imagenesCartas.clear();
        for (Carta carta : Juego.mostrarImgColeccion()) {
            imagenesCartas.add(new ImageIcon(getClass().getResource(carta.getUrl())));
        }
        
    }
}
