/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.gestion_BD;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.*;
import javax.swing.*;
import modelo.EnumRegiones;

/**
 *
 * @author Antonio
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener{
    private javax.swing.JButton[][] cartasItems;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroUsuario = new javax.swing.JFrame();
        panelVacio1Registro = new javax.swing.JPanel();
        panelCentralRegistro = new javax.swing.JPanel();
        textFieldNombreUsuarioRegistro = new javax.swing.JTextField();
        textFieldPasswordUsuarioRegistro = new javax.swing.JTextField();
        textFieldEdadUsuarioRegistro = new javax.swing.JTextField();
        comboBoxRegionesRegistro = new javax.swing.JComboBox<>();
        labelSuperiorRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnReset1 = new javax.swing.JButton();
        btnEnviarRegistro = new javax.swing.JButton();
        btnVolverRegistro = new javax.swing.JButton();
        panelVacio2Registro = new javax.swing.JPanel();
        logIn = new javax.swing.JFrame();
        panelVacio1Login = new javax.swing.JPanel();
        panelCentralLogin = new javax.swing.JPanel();
        textFieldPasswordUsuarioLogIn = new javax.swing.JTextField();
        labelSuperiorRegistro1 = new javax.swing.JLabel();
        labelNombreLogIn = new javax.swing.JLabel();
        labelPWDLogIn = new javax.swing.JLabel();
        textFieldNombreUsuarioLogIn = new javax.swing.JTextField();
        btnResetLogIn = new javax.swing.JButton();
        btnEnviarLogIn = new javax.swing.JButton();
        btnVolverLogIn = new javax.swing.JButton();
        panelVacio2Login = new javax.swing.JPanel();
        dialogLogInFallido = new javax.swing.JDialog();
        panelIconoAviso = new javax.swing.JPanel();
        labelMensaje = new javax.swing.JLabel();
        btnAceptarDialog = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JFrame();
        panelVacio = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panelColeccion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelVacio2 = new javax.swing.JPanel();
        cartaAmpliada = new javax.swing.JDialog();
        panelVacio1 = new javax.swing.JPanel();
        panelCentral1 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelMPT = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        panelVacio3 = new javax.swing.JPanel();

        registroUsuario.setMinimumSize(new java.awt.Dimension(1920, 1080));
        registroUsuario.setResizable(false);
        registroUsuario.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacio1RegistroLayout = new javax.swing.GroupLayout(panelVacio1Registro);
        panelVacio1Registro.setLayout(panelVacio1RegistroLayout);
        panelVacio1RegistroLayout.setHorizontalGroup(
            panelVacio1RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio1RegistroLayout.setVerticalGroup(
            panelVacio1RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        registroUsuario.getContentPane().add(panelVacio1Registro);

        textFieldNombreUsuarioRegistro.setToolTipText("Nombre");
        textFieldNombreUsuarioRegistro.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldNombreUsuarioRegistro.setPreferredSize(new java.awt.Dimension(50, 100));

        textFieldPasswordUsuarioRegistro.setToolTipText("Contraseña");
        textFieldPasswordUsuarioRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldPasswordUsuarioRegistro.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldPasswordUsuarioRegistro.setPreferredSize(new java.awt.Dimension(50, 100));

        textFieldEdadUsuarioRegistro.setToolTipText("Contraseña");
        textFieldEdadUsuarioRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldEdadUsuarioRegistro.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldEdadUsuarioRegistro.setPreferredSize(new java.awt.Dimension(50, 100));
        textFieldEdadUsuarioRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldEdadUsuarioRegistroKeyPressed(evt);
            }
        });

        comboBoxRegionesRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUW", "EUNE", "KOR", "NA", "LATAM", "CHI", "JAP", "RUS", "AFR", "OCE" }));

        labelSuperiorRegistro.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelSuperiorRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuperiorRegistro.setText("Registrar");

        jLabel5.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel6.setText("Región: ");

        jLabel7.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel7.setText("Contraseña:");

        jLabel8.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        jLabel8.setText("Nombre:");

        btnEnviarRegistro.setPreferredSize(new java.awt.Dimension(72, 24));
        btnEnviarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRegistroActionPerformed(evt);
            }
        });

        btnVolverRegistro.setText("Volver");
        btnVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCentralRegistroLayout = new javax.swing.GroupLayout(panelCentralRegistro);
        panelCentralRegistro.setLayout(panelCentralRegistroLayout);
        panelCentralRegistroLayout.setHorizontalGroup(
            panelCentralRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldNombreUsuarioRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textFieldPasswordUsuarioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textFieldEdadUsuarioRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboBoxRegionesRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSuperiorRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCentralRegistroLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(panelCentralRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(panelCentralRegistroLayout.createSequentialGroup()
                .addComponent(btnVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCentralRegistroLayout.setVerticalGroup(
            panelCentralRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralRegistroLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(labelSuperiorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldNombreUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldPasswordUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldEdadUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(comboBoxRegionesRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEnviarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registroUsuario.getContentPane().add(panelCentralRegistro);

        javax.swing.GroupLayout panelVacio2RegistroLayout = new javax.swing.GroupLayout(panelVacio2Registro);
        panelVacio2Registro.setLayout(panelVacio2RegistroLayout);
        panelVacio2RegistroLayout.setHorizontalGroup(
            panelVacio2RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio2RegistroLayout.setVerticalGroup(
            panelVacio2RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        registroUsuario.getContentPane().add(panelVacio2Registro);

        logIn.setMinimumSize(new java.awt.Dimension(1920, 1080));
        logIn.setResizable(false);
        logIn.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacio1LoginLayout = new javax.swing.GroupLayout(panelVacio1Login);
        panelVacio1Login.setLayout(panelVacio1LoginLayout);
        panelVacio1LoginLayout.setHorizontalGroup(
            panelVacio1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio1LoginLayout.setVerticalGroup(
            panelVacio1LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        logIn.getContentPane().add(panelVacio1Login);

        textFieldPasswordUsuarioLogIn.setToolTipText("Contraseña");
        textFieldPasswordUsuarioLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldPasswordUsuarioLogIn.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldPasswordUsuarioLogIn.setPreferredSize(new java.awt.Dimension(50, 100));

        labelSuperiorRegistro1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelSuperiorRegistro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuperiorRegistro1.setText("Iniciar sesión");

        labelNombreLogIn.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        labelNombreLogIn.setText("Nombre:");

        labelPWDLogIn.setFont(new java.awt.Font("Dogica Pixel", 0, 24)); // NOI18N
        labelPWDLogIn.setText("Contraseña:");

        textFieldNombreUsuarioLogIn.setToolTipText("Nombre");
        textFieldNombreUsuarioLogIn.setMinimumSize(new java.awt.Dimension(50, 100));
        textFieldNombreUsuarioLogIn.setPreferredSize(new java.awt.Dimension(50, 100));

        btnResetLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetLogInActionPerformed(evt);
            }
        });

        btnEnviarLogIn.setPreferredSize(new java.awt.Dimension(72, 24));
        btnEnviarLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarLogInActionPerformed(evt);
            }
        });

        btnVolverLogIn.setText("Volver");
        btnVolverLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCentralLoginLayout = new javax.swing.GroupLayout(panelCentralLogin);
        panelCentralLogin.setLayout(panelCentralLoginLayout);
        panelCentralLoginLayout.setHorizontalGroup(
            panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldNombreUsuarioLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPWDLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textFieldPasswordUsuarioLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNombreLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSuperiorRegistro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCentralLoginLayout.createSequentialGroup()
                .addGroup(panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLoginLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviarLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCentralLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolverLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        panelCentralLoginLayout.setVerticalGroup(
            panelCentralLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLoginLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(labelSuperiorRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(labelNombreLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldNombreUsuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPWDLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldPasswordUsuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnEnviarLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(btnVolverLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logIn.getContentPane().add(panelCentralLogin);

        javax.swing.GroupLayout panelVacio2LoginLayout = new javax.swing.GroupLayout(panelVacio2Login);
        panelVacio2Login.setLayout(panelVacio2LoginLayout);
        panelVacio2LoginLayout.setHorizontalGroup(
            panelVacio2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio2LoginLayout.setVerticalGroup(
            panelVacio2LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        logIn.getContentPane().add(panelVacio2Login);

        dialogLogInFallido.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogLogInFallidoWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout panelIconoAvisoLayout = new javax.swing.GroupLayout(panelIconoAviso);
        panelIconoAviso.setLayout(panelIconoAvisoLayout);
        panelIconoAvisoLayout.setHorizontalGroup(
            panelIconoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelIconoAvisoLayout.setVerticalGroup(
            panelIconoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        labelMensaje.setText("Inicio de sesion fallido");

        btnAceptarDialog.setText("Aceptar");
        btnAceptarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogLogInFallidoLayout = new javax.swing.GroupLayout(dialogLogInFallido.getContentPane());
        dialogLogInFallido.getContentPane().setLayout(dialogLogInFallidoLayout);
        dialogLogInFallidoLayout.setHorizontalGroup(
            dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                .addGroup(dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(panelIconoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnAceptarDialog)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        dialogLogInFallidoLayout.setVerticalGroup(
            dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLogInFallidoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(dialogLogInFallidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIconoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnAceptarDialog)
                .addGap(20, 20, 20))
        );

        menuPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuPrincipalFocusGained(evt);
            }
        });
        menuPrincipal.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        menuPrincipal.getContentPane().add(panelVacio);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel15.setText("NUMERO DE MONEDAS");

        jLabel1.setText("AQUI VA EL BUCLE QUE METE LAS CARTAS");

        javax.swing.GroupLayout panelColeccionLayout = new javax.swing.GroupLayout(panelColeccion);
        panelColeccion.setLayout(panelColeccionLayout);
        panelColeccionLayout.setHorizontalGroup(
            panelColeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColeccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
        );
        panelColeccionLayout.setVerticalGroup(
            panelColeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColeccionLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(813, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(panelColeccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelColeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipal.getContentPane().add(panelCentral);

        javax.swing.GroupLayout panelVacio2Layout = new javax.swing.GroupLayout(panelVacio2);
        panelVacio2.setLayout(panelVacio2Layout);
        panelVacio2Layout.setHorizontalGroup(
            panelVacio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio2Layout.setVerticalGroup(
            panelVacio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        menuPrincipal.getContentPane().add(panelVacio2);

        javax.swing.GroupLayout cartaAmpliadaLayout = new javax.swing.GroupLayout(cartaAmpliada.getContentPane());
        cartaAmpliada.getContentPane().setLayout(cartaAmpliadaLayout);
        cartaAmpliadaLayout.setHorizontalGroup(
            cartaAmpliadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        cartaAmpliadaLayout.setVerticalGroup(
            cartaAmpliadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MPT");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelVacio1Layout = new javax.swing.GroupLayout(panelVacio1);
        panelVacio1.setLayout(panelVacio1Layout);
        panelVacio1Layout.setHorizontalGroup(
            panelVacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio1Layout.setVerticalGroup(
            panelVacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(panelVacio1);

        panelTitulo.setEnabled(false);
        panelTitulo.setOpaque(false);

        labelMPT.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelMPT.setForeground(new java.awt.Color(0, 0, 0));
        labelMPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMPT.setText("MPT");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMPT, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(labelMPT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(72, 24));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Medieval Pixel Tokens");

        javax.swing.GroupLayout panelCentral1Layout = new javax.swing.GroupLayout(panelCentral1);
        panelCentral1.setLayout(panelCentral1Layout);
        panelCentral1Layout.setHorizontalGroup(
            panelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCentral1Layout.setVerticalGroup(
            panelCentral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentral1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelCentral1);

        javax.swing.GroupLayout panelVacio3Layout = new javax.swing.GroupLayout(panelVacio3);
        panelVacio3.setLayout(panelVacio3Layout);
        panelVacio3Layout.setHorizontalGroup(
            panelVacio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelVacio3Layout.setVerticalGroup(
            panelVacio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(panelVacio3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEdadUsuarioRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldEdadUsuarioRegistroKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            this.textFieldEdadUsuarioRegistro.setEditable(true);
            try {
                Integer.valueOf(this.textFieldEdadUsuarioRegistro.getText());
            } catch (NumberFormatException e) {
                this.textFieldEdadUsuarioRegistro.setText("");
            }
        } else {
            this.textFieldEdadUsuarioRegistro.setText("* Introduce solo números(0-9)");
        }
    }//GEN-LAST:event_textFieldEdadUsuarioRegistroKeyPressed

    private void btnEnviarLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarLogInActionPerformed
        if (!(gestion_BD.iniciarSesion(this.textFieldNombreUsuarioLogIn.getText(),
                this.textFieldPasswordUsuarioLogIn.getText()))) { // Si no se puede iniciar sesión
            
            this.dialogLogInFallido.setVisible(true);
            this.logIn.setFocusable(false);
        }else{
            this.menuPrincipal.setVisible(true);
            this.logIn.setVisible(false);
        }
    }//GEN-LAST:event_btnEnviarLogInActionPerformed

    private void btnResetLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetLogInActionPerformed
        this.textFieldNombreUsuarioLogIn.setText("");
        this.textFieldPasswordUsuarioLogIn.setText("");
    }//GEN-LAST:event_btnResetLogInActionPerformed

    private void btnEnviarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRegistroActionPerformed
        if (gestion_BD.altaUsuario( textFieldNombreUsuarioRegistro.getText(),
                                    textFieldPasswordUsuarioRegistro.getText(),
                                    Integer.parseInt(textFieldEdadUsuarioRegistro.getText()),
                                    comboBoxRegionesRegistro.getSelectedItem().toString())) {
            
        }
    }//GEN-LAST:event_btnEnviarRegistroActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        this.logIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        this.registroUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnAceptarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDialogActionPerformed
        this.textFieldNombreUsuarioLogIn.setText("");
        this.textFieldPasswordUsuarioLogIn.setText("");
    }//GEN-LAST:event_btnAceptarDialogActionPerformed

    private void btnVolverLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLogInActionPerformed
        this.logIn.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnVolverLogInActionPerformed

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        this.registroUsuario.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void dialogLogInFallidoWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogLogInFallidoWindowClosed
        this.textFieldNombreUsuarioLogIn.setText("");
        this.textFieldPasswordUsuarioLogIn.setText("");
    }//GEN-LAST:event_dialogLogInFallidoWindowClosed

    private void menuPrincipalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuPrincipalFocusGained
        crearEspacioDeCartas();
    }//GEN-LAST:event_menuPrincipalFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    public void crearEspacioDeCartas(){
        for (JButton[] cartasItem : cartasItems) {
            for (int j = 0; j < cartasItems.length; j++) {
                cartasItem[j] = new javax.swing.JButton(); //inicio boton
                panelColeccion.add(cartasItem[j]); //añado boton al panel para que se vea
                // TODO poner en el actionListener una clase donde se usará el evento cartasItems[j].addActionListener(this);//le digo que el boton lance eventos
                cartasItem[j].addActionListener(this);
                cartasItem[j].setBackground(new Color(245,245,245)); //color del fonto del boton
                cartasItem[j].setFocusable(false); //esto hace que no se pueda enfocar el boton y no salga un recuadro raro feo
                cartasItem[j].setFont(new Font("Arial",Font.BOLD,120)); //la font de las letras dentro del boton
            }
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarDialog;
    private javax.swing.JButton btnEnviarLogIn;
    private javax.swing.JButton btnEnviarRegistro;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnResetLogIn;
    private javax.swing.JButton btnVolverLogIn;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JDialog cartaAmpliada;
    private javax.swing.JComboBox<String> comboBoxRegionesRegistro;
    private javax.swing.JDialog dialogLogInFallido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelMPT;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelNombreLogIn;
    private javax.swing.JLabel labelPWDLogIn;
    private javax.swing.JLabel labelSuperiorRegistro;
    private javax.swing.JLabel labelSuperiorRegistro1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JFrame logIn;
    private javax.swing.JFrame menuPrincipal;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCentral1;
    private javax.swing.JPanel panelCentralLogin;
    private javax.swing.JPanel panelCentralRegistro;
    private javax.swing.JPanel panelColeccion;
    private javax.swing.JPanel panelIconoAviso;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel panelVacio1;
    private javax.swing.JPanel panelVacio1Login;
    private javax.swing.JPanel panelVacio1Registro;
    private javax.swing.JPanel panelVacio2;
    private javax.swing.JPanel panelVacio2Login;
    private javax.swing.JPanel panelVacio2Registro;
    private javax.swing.JPanel panelVacio3;
    private javax.swing.JFrame registroUsuario;
    private javax.swing.JTextField textFieldEdadUsuarioRegistro;
    private javax.swing.JTextField textFieldNombreUsuarioLogIn;
    private javax.swing.JTextField textFieldNombreUsuarioRegistro;
    private javax.swing.JTextField textFieldPasswordUsuarioLogIn;
    private javax.swing.JTextField textFieldPasswordUsuarioRegistro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JLabel labelimagen = new JLabel("", JLabel.CENTER);
        ImageIcon fotoCarta = new ImageIcon(getClass().getResource("/resources/img/Alquimista_card.png"));
        Image scaledImage = fotoCarta.getImage();
        scaledImage = scaledImage.getScaledInstance(fotoCarta.getIconWidth()*2, fotoCarta.getIconHeight() * 2, java.awt.Image.SCALE_SMOOTH);
        fotoCarta = new ImageIcon(scaledImage);
        labelimagen.setIcon(fotoCarta);
        labelimagen.setSize(fotoCarta.getIconWidth(), fotoCarta.getIconHeight());
        cartaAmpliada.add(labelimagen);
        cartaAmpliada.setSize(fotoCarta.getIconWidth()+16, fotoCarta.getIconHeight()+39);
        cartaAmpliada.setLocationRelativeTo(null);
        cartaAmpliada.setVisible(true);
    }
}
